#!/bin/bash

find ~ -maxdepth 1 -type f

#Output:

#/home/surya/.bash_logout
#/home/surya/.bashrc
#/home/surya/.ICEauthority
#/home/surya/.esd_auth
#/home/surya/.bash_history
#/home/surya/.bash_profile.swo
#/home/surya/.bash_profile
#/home/surya/.lesshst
#/home/surya/.viminfo


# Used find command in home directory setting maxdepth to 1 to just query that folder
# and set type as f to just query the files. 

# Since my home directory contails only hidden files so only those I've mentioned in output
# If you want just the file names then you can just use cut and get only the file names like this:-

# find ~ -maxdepth 1 -type f | cut -d'/' -f4

# Output
#.bash_logout
#.bashrc
#.ICEauthority
#.esd_auth
#.bash_history
#.bash_profile.swo
#.bash_profile
#.lesshst
#.viminfo




